services:
  db:
    image: mariadb:latest
    container_name: ${DB_HOST}
    restart: always
    ports:
      - "3306:3306"
    env_file: ./.env
    environment:
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    healthcheck:
      test: ["CMD", "echo", "show databases;", "|", "mysql", "--user=${DB_USERNAME}", "--password=${DB_PASSWORD}", "--host=127.0.0.1", "--port=${DB_PORT}", "--database=${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 3
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file: ./.env